//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAWebHost.GAWebServant {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GAWebServant.IWorker")]
    public interface IWorker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorker/MInitialize", ReplyAction="http://tempuri.org/IWorker/MInitializeResponse")]
        void MInitialize(int aiSizePop, int aiNumCities, float afRateMutate, float afRateCross, int[][] aiDistMat, int aiWorkerNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorker/MInitialize", ReplyAction="http://tempuri.org/IWorker/MInitializeResponse")]
        System.Threading.Tasks.Task MInitializeAsync(int aiSizePop, int aiNumCities, float afRateMutate, float afRateCross, int[][] aiDistMat, int aiWorkerNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorker/MRun", ReplyAction="http://tempuri.org/IWorker/MRunResponse")]
        void MRun(int aiIterations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorker/MRun", ReplyAction="http://tempuri.org/IWorker/MRunResponse")]
        System.Threading.Tasks.Task MRunAsync(int aiIterations);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkerChannel : GAWebHost.GAWebServant.IWorker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkerClient : System.ServiceModel.ClientBase<GAWebHost.GAWebServant.IWorker>, GAWebHost.GAWebServant.IWorker {
        
        public WorkerClient() {
        }
        
        public WorkerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MInitialize(int aiSizePop, int aiNumCities, float afRateMutate, float afRateCross, int[][] aiDistMat, int aiWorkerNum) {
            base.Channel.MInitialize(aiSizePop, aiNumCities, afRateMutate, afRateCross, aiDistMat, aiWorkerNum);
        }
        
        public System.Threading.Tasks.Task MInitializeAsync(int aiSizePop, int aiNumCities, float afRateMutate, float afRateCross, int[][] aiDistMat, int aiWorkerNum) {
            return base.Channel.MInitializeAsync(aiSizePop, aiNumCities, afRateMutate, afRateCross, aiDistMat, aiWorkerNum);
        }
        
        public void MRun(int aiIterations) {
            base.Channel.MRun(aiIterations);
        }
        
        public System.Threading.Tasks.Task MRunAsync(int aiIterations) {
            return base.Channel.MRunAsync(aiIterations);
        }
    }
}
