//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondWCFClient.MM2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Matrix", Namespace="http://schemas.datacontract.org/2004/07/SecondWCF")]
    [System.SerializableAttribute()]
    public partial class Matrix : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cols {
            get {
                return this.ColsField;
            }
            set {
                if ((this.ColsField.Equals(value) != true)) {
                    this.ColsField = value;
                    this.RaisePropertyChanged("Cols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((this.RowsField.Equals(value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MM2.IMyMath2")]
    public interface IMyMath2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath2/MultiplyMatrix", ReplyAction="http://tempuri.org/IMyMath2/MultiplyMatrixResponse")]
        SecondWCFClient.MM2.Matrix MultiplyMatrix(SecondWCFClient.MM2.Matrix A, SecondWCFClient.MM2.Matrix B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath2/MultiplyMatrix", ReplyAction="http://tempuri.org/IMyMath2/MultiplyMatrixResponse")]
        System.Threading.Tasks.Task<SecondWCFClient.MM2.Matrix> MultiplyMatrixAsync(SecondWCFClient.MM2.Matrix A, SecondWCFClient.MM2.Matrix B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath2/InitMatrix", ReplyAction="http://tempuri.org/IMyMath2/InitMatrixResponse")]
        SecondWCFClient.MM2.Matrix InitMatrix(int rows, int cols);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath2/InitMatrix", ReplyAction="http://tempuri.org/IMyMath2/InitMatrixResponse")]
        System.Threading.Tasks.Task<SecondWCFClient.MM2.Matrix> InitMatrixAsync(int rows, int cols);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyMath2Channel : SecondWCFClient.MM2.IMyMath2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMath2Client : System.ServiceModel.ClientBase<SecondWCFClient.MM2.IMyMath2>, SecondWCFClient.MM2.IMyMath2 {
        
        public MyMath2Client() {
        }
        
        public MyMath2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMath2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMath2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMath2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SecondWCFClient.MM2.Matrix MultiplyMatrix(SecondWCFClient.MM2.Matrix A, SecondWCFClient.MM2.Matrix B) {
            return base.Channel.MultiplyMatrix(A, B);
        }
        
        public System.Threading.Tasks.Task<SecondWCFClient.MM2.Matrix> MultiplyMatrixAsync(SecondWCFClient.MM2.Matrix A, SecondWCFClient.MM2.Matrix B) {
            return base.Channel.MultiplyMatrixAsync(A, B);
        }
        
        public SecondWCFClient.MM2.Matrix InitMatrix(int rows, int cols) {
            return base.Channel.InitMatrix(rows, cols);
        }
        
        public System.Threading.Tasks.Task<SecondWCFClient.MM2.Matrix> InitMatrixAsync(int rows, int cols) {
            return base.Channel.InitMatrixAsync(rows, cols);
        }
    }
}
