//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWCFClient.FRWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FRWCF.IMyMath")]
    public interface IMyMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/ComputeAvg", ReplyAction="http://tempuri.org/IMyMath/ComputeAvgResponse")]
        double ComputeAvg(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/ComputeAvg", ReplyAction="http://tempuri.org/IMyMath/ComputeAvgResponse")]
        System.Threading.Tasks.Task<double> ComputeAvgAsync(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/FindMin", ReplyAction="http://tempuri.org/IMyMath/FindMinResponse")]
        int FindMin(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/FindMin", ReplyAction="http://tempuri.org/IMyMath/FindMinResponse")]
        System.Threading.Tasks.Task<int> FindMinAsync(int a, int b, int c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyMathChannel : FirstWCFClient.FRWCF.IMyMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMathClient : System.ServiceModel.ClientBase<FirstWCFClient.FRWCF.IMyMath>, FirstWCFClient.FRWCF.IMyMath {
        
        public MyMathClient() {
        }
        
        public MyMathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ComputeAvg(int a, int b, int c) {
            return base.Channel.ComputeAvg(a, b, c);
        }
        
        public System.Threading.Tasks.Task<double> ComputeAvgAsync(int a, int b, int c) {
            return base.Channel.ComputeAvgAsync(a, b, c);
        }
        
        public int FindMin(int a, int b, int c) {
            return base.Channel.FindMin(a, b, c);
        }
        
        public System.Threading.Tasks.Task<int> FindMinAsync(int a, int b, int c) {
            return base.Channel.FindMinAsync(a, b, c);
        }
    }
}
