//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAWebClient.Host {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Host.IDistributor")]
    public interface IDistributor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributor/MExecute", ReplyAction="http://tempuri.org/IDistributor/MExecuteResponse")]
        void MExecute(int[][] aiDistMat, int aiNumWorkers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributor/MExecute", ReplyAction="http://tempuri.org/IDistributor/MExecuteResponse")]
        System.Threading.Tasks.Task MExecuteAsync(int[][] aiDistMat, int aiNumWorkers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistributorChannel : GAWebClient.Host.IDistributor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributorClient : System.ServiceModel.ClientBase<GAWebClient.Host.IDistributor>, GAWebClient.Host.IDistributor {
        
        public DistributorClient() {
        }
        
        public DistributorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MExecute(int[][] aiDistMat, int aiNumWorkers) {
            base.Channel.MExecute(aiDistMat, aiNumWorkers);
        }
        
        public System.Threading.Tasks.Task MExecuteAsync(int[][] aiDistMat, int aiNumWorkers) {
            return base.Channel.MExecuteAsync(aiDistMat, aiNumWorkers);
        }
    }
}
